# Generated by Django 4.2.2 on 2023-09-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Album name')),
                ('photo', models.ImageField(default='', upload_to='static/img/album', verbose_name='Album photo')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Singer's name")),
                ('photo', models.ImageField(default='', upload_to='static/img/singer', verbose_name="Singer's photo")),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='Song name')),
                ('albums', models.ManyToManyField(related_name='songs', to='music_items.album')),
                ('singers', models.ManyToManyField(related_name='songs', to='music_items.singer')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_items.singer'),
        ),
    ]
