# Generated by Django 4.2.6 on 2023-10-25 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Publication Date'),
            preserve_default=False,
        ),
    ]
