# Generated by Django 4.2.6 on 2023-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_items', '0002_song_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='default_audio.mp3', upload_to='audio/', verbose_name='Audio File'),
        ),
    ]
