# Generated by Django 4.2.7 on 2023-12-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_items', '0011_singer_banner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Release Year'),
        ),
    ]
