# Generated by Django 4.2.7 on 2023-12-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_items', '0012_album_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='static/img/genre/default.jpg', upload_to='img/genre/', verbose_name='Genre Image'),
        ),
    ]
