# Generated by Django 4.2.7 on 2023-12-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_items', '0013_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='banner_photo',
            field=models.ImageField(default='static/img/genre_banner/default_banner.jpg', upload_to='img/genre_banner/', verbose_name='Banner Photo'),
        ),
    ]
